#联系 spring.factories
#在我们这配置文件中能配置的东西， 都存在一个固有的规律
#xxxAotoConfiguration:默认值 xxxPropertise 和 配置文件绑定，我们就可以使用自定义的配置了！
student:
  name: ${random.uuid}
  age: ${random.int}
  list:
    - cat
    - dog
  map: {k1: v1,k2: v2}
  #${student.hello:good} 表示如果student.hello这个值存在就是本值，如果不存在就是good
spring:
  profiles:
    active: dev
  messages:
    basename: i18n.login
  mvc:
    date-format: yyyy-MM-dd
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/jdbctest?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
server:
  servlet:
    context-path: /zhoufan
mybatis:
  type-aliases-package: com.bdqn.config.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    auto-mapping-behavior: full













---
server:
  port: 8081
spring:
  profiles: dev
---
server:
  port: 8082
spring:
  profiles: test
